Repository duozone-1-finalproject/AI, pull requests merged in 2025-09, with the labels that each got.

#37 merge/kafka-ljh
  build.gradle
  src/main/java/com/example/demo/config/KafkaConfig.java
  src/main/java/com/example/demo/dto/Ai_Server_RequestDto.java
  src/main/java/com/example/demo/dto/Ai_Server_ResponseDto.java
  src/main/java/com/example/demo/kafka/KafkaReportConsumer.java
  src/main/resources/application.yml
Labels: documentation

#65 docs: #64 README update
  README.md
Labels: documentation

#69 Feat/kafakall
  src/main/java/com/example/demo/dto/kafka/Ai_Server_RequestDto.java
  src/main/java/com/example/demo/dto/kafka/Ai_Server_ResponseDto.java
  src/main/java/com/example/demo/graphmain/nodes/ValidatorGraphInvokerNode.java
  src/main/java/com/example/demo/kafka/KafkaReportConsumer.java
  src/main/java/com/example/demo/service/graphvalidator/impl/CheckServiceImpl.java
  src/main/resources/prompts/risk_industry_checklist.st
Labels: bug

#71 Feat/#70 webgraph article pop edge
  src/main/java/com/example/demo/config/AiClientConfig.java
  src/main/java/com/example/demo/dto/WebDocs.java
  src/main/java/com/example/demo/graphweb/WebConfig.java
  src/main/java/com/example/demo/graphweb/WebState.java
  src/main/java/com/example/demo/graphweb/nodes/AfterValidationNode.java
  src/main/java/com/example/demo/graphweb/nodes/PickedArticleNode.java
  src/main/java/com/example/demo/graphweb/nodes/ValidationNode.java
  src/main/java/com/example/demo/validatorgraph/nodes/AdjustDraftNode.java
  src/main/java/com/example/demo/validatorgraph/nodes/GlobalValidatorNode.java
Labels: enhancement

#78 Feat/#72 search node
  .gitignore
  src/main/java/com/example/demo/constants/WebConstants.java
  src/main/java/com/example/demo/controller/WebController.java
  src/main/java/com/example/demo/dto/SearchEnvelope.java
  src/main/java/com/example/demo/dto/SearchLLMDto.java
  src/main/java/com/example/demo/graphweb/nodes/AfterValidationNode.java
  src/main/java/com/example/demo/graphweb/nodes/FetchNode.java
  src/main/java/com/example/demo/graphweb/nodes/QueryBuilderNode.java
  src/main/java/com/example/demo/graphweb/nodes/SearchNode.java
  src/main/java/com/example/demo/jsonschema/SearchSchemas.java
  src/main/java/com/example/demo/langgraph.zip
  src/main/resources/application.yml
  src/main/resources/prompts/search_sys.st
  src/main/resources/prompts/search_user.st
Labels: documentation, enhancement

#80 kafkaAIaa#24
  src/main/java/com/example/demo/config/KafkaConfig.java
  src/main/java/com/example/demo/kafka/KafkaReportConsumer.java
  src/main/resources/application.yml
Labels: bug

#83 Update CheckServiceImpl.java
  src/main/java/com/example/demo/service/graphvalidator/impl/CheckServiceImpl.java
Labels: bug, documentation

#86 Task/#85 web refactoring
  src/main/java/com/example/demo/config/KafkaConfig.java
  src/main/java/com/example/demo/constants/WebConstants.java
  src/main/java/com/example/demo/constants/YamlConstants.java
  src/main/java/com/example/demo/controller/WebController.java
  src/main/java/com/example/demo/dto/graphweb/ContextDoc.java
  src/main/java/com/example/demo/dto/graphweb/FetchLLMDto.java
  src/main/java/com/example/demo/dto/graphweb/SearchEnvelope.java
  src/main/java/com/example/demo/dto/graphweb/SearchLLMDto.java
  src/main/java/com/example/demo/dto/graphweb/ValidationResultDto.java
  src/main/java/com/example/demo/dto/graphweb/WebDocs.java
  src/main/java/com/example/demo/graphmain/DraftGraphConfig.java
  src/main/java/com/example/demo/graphmain/DraftState.java
  src/main/java/com/example/demo/graphmain/nodes/ContextAggregatorNode.java
  src/main/java/com/example/demo/graphmain/nodes/DbSubgraphInvoker.java
  src/main/java/com/example/demo/graphmain/nodes/WebSubgraphInvoker.java
  src/main/java/com/example/demo/graphweb/WebConfig.java
  src/main/java/com/example/demo/graphweb/WebState.java
  src/main/java/com/example/demo/graphweb/nodes/AfterValidationNode.java
  src/main/java/com/example/demo/graphweb/nodes/FetchNode.java
  src/main/java/com/example/demo/graphweb/nodes/PickedArticleNode.java
  src/main/java/com/example/demo/graphweb/nodes/ProcessNode.java
  src/main/java/com/example/demo/graphweb/nodes/SearchNode.java
  src/main/java/com/example/demo/graphweb/nodes/ValidationNode.java
  src/main/java/com/example/demo/langgraph/DraftGraphConfig.java
  src/main/java/com/example/demo/langgraph/nodes/DraftGeneratorNode.java
  src/main/java/com/example/demo/langgraph/state/DraftState.java
  src/main/java/com/example/demo/service/graphmain/impl/GraphServiceImpl.java
  src/main/java/com/example/demo/service/graphweb/WebService.java
  src/main/java/com/example/demo/validatorgraph/nodes/AdjustDraftNode.java
  src/main/java/com/example/demo/validatorgraph/nodes/GlobalValidatorNode.java
Labels: bug, documentation, enhancement
