Repository duozone-1-finalproject/AI, pull requests merged in 2025-08, with the labels that each got.

#5 뉴스 크롤링 기능구현 완료
  build.gradle
Labels: documentation, enhancement

#8 docs: #7 전체 리팩토링(랭그래프 기본구현 구조)
  .gitignore
  build.gradle
  src/main/java/com/example/demo/DemoApplication.java
  src/main/java/com/example/demo/ServletInitializer.java
  src/main/java/com/example/demo/config/DotEnvConfig.java
  src/main/java/com/example/demo/controller/GraphController.java
  src/main/java/com/example/demo/controller/SerpApiController.java
  src/main/java/com/example/demo/dto/LangGraphDto.java
  src/main/java/com/example/demo/dto/SerpApiResult.java
  src/main/java/com/example/demo/dto/SerpApiSearchResponse.java
  src/main/java/com/example/demo/langgraph/GraphConfig.java
  src/main/java/com/example/demo/langgraph/node/LlmNode.java
  src/main/java/com/example/demo/langgraph/state/ChannelKeys.java
  src/main/java/com/example/demo/langgraph/state/StateConfig.java
  src/main/java/com/example/demo/service/GraphService.java
  src/main/java/com/example/demo/service/GraphServiceImpl.java
  src/main/java/com/example/demo/service/LlmService.java
  src/main/java/com/example/demo/service/LlmServiceImpl.java
  src/main/java/com/example/demo/service/SerpApiService.java
  src/main/java/com/example/demo/util/FileWriterUtil.java
  src/main/java/com/example/demo/util/JsonWriter.java
  src/main/resources/application.yml
Labels: documentation, enhancement

#9 Main 랭그래프 구조 구성 / Opensearch 연결 설정
  build.gradle
  src/main/java/com/example/demo/DemoApplication.java
  src/main/java/com/example/demo/config/AiClientConfig.java
  src/main/java/com/example/demo/config/AiSectionProperties.java
  src/main/java/com/example/demo/config/AppConfig.java
  src/main/java/com/example/demo/constants/CommonConstant.java
  src/main/java/com/example/demo/controller/GraphController.java
  src/main/java/com/example/demo/dto/ContextDoc.java
  src/main/java/com/example/demo/dto/DraftRequestDto.java
  src/main/java/com/example/demo/dto/DraftResponseDto.java
  src/main/java/com/example/demo/dto/LangGraphDto.java
  src/main/java/com/example/demo/langgraph/DraftGraphConfig.java
  src/main/java/com/example/demo/langgraph/GraphConfig.java
  src/main/java/com/example/demo/langgraph/node/LlmNode.java
  src/main/java/com/example/demo/langgraph/nodes/ContextAggregatorNode.java
  src/main/java/com/example/demo/langgraph/nodes/DraftGeneratorNode.java
  src/main/java/com/example/demo/langgraph/nodes/GlobalValidatorNode.java
  src/main/java/com/example/demo/langgraph/nodes/PromptSelectorNode.java
  src/main/java/com/example/demo/langgraph/nodes/RetryAdjustNode.java
  src/main/java/com/example/demo/langgraph/nodes/SourceSelectorNode.java
  src/main/java/com/example/demo/langgraph/state/ChannelKeys.java
  src/main/java/com/example/demo/langgraph/state/DraftGraphWiring.java
  src/main/java/com/example/demo/langgraph/state/DraftState.java
  src/main/java/com/example/demo/langgraph/state/StateConfig.java
  src/main/java/com/example/demo/opensearch/IndexBootstrap.java
  src/main/java/com/example/demo/opensearch/OpensearchConfig.java
  src/main/java/com/example/demo/opensearch/OpensearchIndexRegistry.java
  src/main/java/com/example/demo/opensearch/OpensearchProperties.java
  src/main/java/com/example/demo/opensearch/ReportSearchService.java
  src/main/java/com/example/demo/service/GraphService.java
  src/main/java/com/example/demo/service/GraphServiceImpl.java
  src/main/java/com/example/demo/service/LlmService.java
  src/main/java/com/example/demo/service/LlmServiceImpl.java
  src/main/java/com/example/demo/service/PromptCatalogService.java
  src/main/java/com/example/demo/service/SourcePolicyService.java
  src/main/java/com/example/demo/util/HtmlUtils.java
  src/main/resources/application.yml
  src/main/resources/opensearch/report_base.json
  src/main/resources/opensearch/standard.json
  src/main/resources/prompts/risk_company.st
  src/main/resources/prompts/risk_etc.st
  src/main/resources/prompts/risk_industry.st
Labels: enhancement

#11 Dev -> Main
  .gitignore
  build.gradle
  src/main/java/com/example/demo/DemoApplication.java
  src/main/java/com/example/demo/ServletInitializer.java
  src/main/java/com/example/demo/config/AiClientConfig.java
  src/main/java/com/example/demo/config/AiSectionProperties.java
  src/main/java/com/example/demo/config/AppConfig.java
  src/main/java/com/example/demo/config/DotEnvConfig.java
  src/main/java/com/example/demo/constants/CommonConstant.java
  src/main/java/com/example/demo/controller/GraphController.java
  src/main/java/com/example/demo/controller/SerpApiController.java
  src/main/java/com/example/demo/dto/ContextDoc.java
  src/main/java/com/example/demo/dto/DraftRequestDto.java
  src/main/java/com/example/demo/dto/DraftResponseDto.java
  src/main/java/com/example/demo/dto/SerpApiResult.java
  src/main/java/com/example/demo/dto/SerpApiSearchResponse.java
  src/main/java/com/example/demo/langgraph/DraftGraphConfig.java
  src/main/java/com/example/demo/langgraph/nodes/ContextAggregatorNode.java
  src/main/java/com/example/demo/langgraph/nodes/DraftGeneratorNode.java
  src/main/java/com/example/demo/langgraph/nodes/GlobalValidatorNode.java
  src/main/java/com/example/demo/langgraph/nodes/PromptSelectorNode.java
  src/main/java/com/example/demo/langgraph/nodes/RetryAdjustNode.java
  src/main/java/com/example/demo/langgraph/nodes/SourceSelectorNode.java
  src/main/java/com/example/demo/langgraph/state/DraftGraphWiring.java
  src/main/java/com/example/demo/langgraph/state/DraftState.java
  src/main/java/com/example/demo/opensearch/IndexBootstrap.java
  src/main/java/com/example/demo/opensearch/OpensearchConfig.java
  src/main/java/com/example/demo/opensearch/OpensearchIndexRegistry.java
  src/main/java/com/example/demo/opensearch/OpensearchProperties.java
  src/main/java/com/example/demo/opensearch/ReportSearchService.java
  src/main/java/com/example/demo/service/GraphService.java
  src/main/java/com/example/demo/service/GraphServiceImpl.java
  src/main/java/com/example/demo/service/PromptCatalogService.java
  src/main/java/com/example/demo/service/SerpApiService.java
  src/main/java/com/example/demo/service/SourcePolicyService.java
  src/main/java/com/example/demo/util/FileWriterUtil.java
  src/main/java/com/example/demo/util/HtmlUtils.java
  src/main/java/com/example/demo/util/JsonWriter.java
  src/main/resources/application.yml
  src/main/resources/opensearch/report_base.json
  src/main/resources/opensearch/standard.json
  src/main/resources/prompts/risk_company.st
  src/main/resources/prompts/risk_etc.st
  src/main/resources/prompts/risk_industry.st
Labels: enhancement

#19 Feat/#18 asyn section
  LICENSE
  README.md
  build.gradle
  src/main/java/com/example/demo/dto/DraftResponseDto.java
  src/main/java/com/example/demo/langgraph/DraftGraphConfig.java
  src/main/java/com/example/demo/service/GraphServiceImpl.java
  src/main/resources/application.yml
Labels: enhancement

#22 bug: #20 spring-ai 충돌버그 수정
  src/main/resources/application.yml
Labels: bug, enhancement
